// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzNPHzic7UDF03jpJUPJTRyrCLC7WrtVg',
    appId: '1:200061896914:web:eae247d206216bd2ce050b',
    messagingSenderId: '200061896914',
    projectId: 'mentor-connect-x',
    authDomain: 'mentor-connect-x.firebaseapp.com',
    storageBucket: 'mentor-connect-x.firebasestorage.app',
    measurementId: 'G-1672D22868',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPC1oV3wVhcGhBl6pnwRue5mXfUXMSOA',
    appId: '1:200061896914:android:df63dcbeb158e34fce050b',
    messagingSenderId: '200061896914',
    projectId: 'mentor-connect-x',
    storageBucket: 'mentor-connect-x.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcW5fDeKVSBeuGJc8QtdtOhxGGhFsXxPM',
    appId: '1:200061896914:ios:546b1b4f156c9605ce050b',
    messagingSenderId: '200061896914',
    projectId: 'mentor-connect-x',
    storageBucket: 'mentor-connect-x.firebasestorage.app',
    iosBundleId: 'com.example.mentorConnectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcW5fDeKVSBeuGJc8QtdtOhxGGhFsXxPM',
    appId: '1:200061896914:ios:546b1b4f156c9605ce050b',
    messagingSenderId: '200061896914',
    projectId: 'mentor-connect-x',
    storageBucket: 'mentor-connect-x.firebasestorage.app',
    iosBundleId: 'com.example.mentorConnectx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzNPHzic7UDF03jpJUPJTRyrCLC7WrtVg',
    appId: '1:200061896914:web:85e7cacfa1c033cdce050b',
    messagingSenderId: '200061896914',
    projectId: 'mentor-connect-x',
    authDomain: 'mentor-connect-x.firebaseapp.com',
    storageBucket: 'mentor-connect-x.firebasestorage.app',
    measurementId: 'G-RLWK61C2FT',
  );

}